### ISSUE TITLE
DER is different after roundtrip to PEM

### ISSUE THREAD

**Issue by TheComamba** [rustls/rcgen#178] opened 2023-10-18 14:10 UTC
If I generate a certificate and call the serialize_der function, the result is different from when I call the serialize_pem function, write it to file, and convert it back to DER. I tested the conversion from PEM to DER with rustls_pemfile, but also with https://www.sslshopper.com/ssl-converter.html. Notably, the 4. Byte of the DER is always 1 larger after the roundtrip.

Is this expected or buggy behaviour? If expected, can someone point me to the reason, and how I can circumvent it (because I'd like to compare the values in a unit test)?

Here's a minimal working example:
```rust
use rcgen::generate_simple_self_signed;
use rustls_pemfile::certs;
use std::{
    fs::{self, File},
    io::BufReader,
    path::PathBuf,
};

fn main() {
    let pem_path_buf = PathBuf::from(String::from("test.pem"));
    let subject_alt_names = vec!["*.test.com".to_string()];
    let cert = generate_simple_self_signed(subject_alt_names).unwrap();
    let pem = cert.serialize_pem().unwrap();
    let direct_der = cert.serialize_der().unwrap();
    fs::write(&pem_path_buf, &pem).unwrap();
    let pem_file = File::open(pem_path_buf).unwrap();
    let certs = certs(&mut BufReader::new(pem_file)).unwrap();
    let der_from_pem = certs[0].clone();
    println!("Directly serialized DER:\n{:?}", direct_der);
    println!("DER after roundtrip:\n{:?}", der_from_pem);
    assert_eq!(direct_der, der_from_pem);
}
```

The dependencies are:
```toml
[dependencies]
rcgen = "0.11.0"
rustls-pemfile = "1.0.2"
```

**Comment by est31** [comment] 2023-10-18 15:07
known dupe of #62 . as a workaround, either only call the pem function or the der function and then do the conversions yourself.

**Closed** 2023-10-18 18:55 UTC
